
# > ***"In order to achieve big, start with something small" __Zunair***




# **Pytorch Full Tutorial**

Core-Features
1. Tensor Computations
2. GPU acceleration
3. Dynamic Computation Graph
4. Automatic Differentiation
5. Distributed Training
6. Interoperability with other libraries

# **Tensors in Pytorch**
Tensor(data-structure) is a specialized multi-dimensional array designed for mathematical and computational efficiency


*   Scalars - 0d tensors
*   Vectors - 1d tenors
*   Matrices - 2d tensors





In [2]:
import torch
if torch.cuda.is_available():
  print("GPU available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available")

GPU available
Using GPU:Tesla T4


# **Creating Tensors**

In [3]:
#empty
torch.empty(2,4) #shows values on the mem locations

tensor([[0.0000e+00, 1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
#zeros and ones
torch.zeros(1,3)
torch.ones(1,3)


tensor([[1., 1., 1.]])

In [5]:
#rand
torch.rand(1,3) #everytime values changes



tensor([[0.1471, 0.5412, 0.0331]])

In [6]:
#define seed to retain rand values
torch.manual_seed(42)
torch.rand(1,3)

tensor([[0.8823, 0.9150, 0.3829]])

In [7]:
#using tensor
torch.tensor([1,2,5,2,3])

tensor([1, 2, 5, 2, 3])



> Some other functions are arange(),linspace(),eye(),full() same as numpy



# **Tensor Shapes**

In [8]:
tensor_x = torch.tensor([[2,3,4,1,2,3],[2,6,4,1,7,3]])
print(tensor_x)
tensor_x.shape

tensor([[2, 3, 4, 1, 2, 3],
        [2, 6, 4, 1, 7, 3]])


torch.Size([2, 6])

In [9]:
#copy the shape of a tensor
copy_x = torch.empty_like(tensor_x)
print(copy_x)

#same for zeros_like and ones_like

tensor([[137575431802920,      4294967296,       368769696,       290458960,
                       0,       368763136],
        [      340452080, 137571363954416,               0,               0,
                       0,               0]])


In [10]:
#torch.rand_like(tensor_x won't work because data_type of tensor_x is INT while rand function uses FLOAT. So explicit mentioning is required)



# **Data Types**

In [11]:
tensor_x.dtype

torch.int64

In [12]:
#Let's solve the rand problem now
rand_x = torch.rand(2,3,dtype=torch.float16)
print(rand_x)
rand_x.dtype

tensor([[0.6318, 0.5518, 0.5347],
        [0.8418, 0.5098, 0.7998]], dtype=torch.float16)


torch.float16

# **Mathematical Operations**

1. Scalar Operation

In [13]:
y = torch.rand(2,2)

#addition
y+2
#subtraction
y-2
#multiplication
y*2
#Divison
y / 2
#Floor division
(y*100) // 2

tensor([[ 6., 46.],
        [29., 43.]])

**Element wise ops can be applied to the same tensor shapes**

# **2. Reduction Operation**

In [14]:
#SUM

red = torch.randint(size=(2,3), low=0, high=10)
#sum
sum = torch.sum(red)
print("Sum is",sum)
#sum along cols
sum_cols = torch.sum(red,dim=0)
print("Sum along cols is",sum_cols)
#sum along rows
sum_rows = torch.sum(red,dim=1)
print("Sum along rows is",sum_rows)

#Same with mean and median, product, Std, argmax, argmin etc

Sum is tensor(24)
Sum along cols is tensor([9, 6, 9])
Sum along rows is tensor([ 7, 17])


# **3. Matrix Operations**

In [15]:
a = torch.randint(size=(2,3), low=0, high=10)
b = torch.randint(size=(3,4), low=0, high=10)

torch.matmul(a,b) #broadcast (2x3) x (3,4) -> 2x4

tensor([[153,  42,  78, 141],
        [ 99,  32,  63, 107]])

In [16]:
#Dot product

vector1 = torch.tensor([2,3])
vector2 = torch.tensor([2,3])

torch.dot(vector1,vector2)

tensor(13)

In [17]:
b

tensor([[3, 1, 9, 7],
        [9, 2, 0, 5],
        [9, 3, 4, 9]])

In [18]:
#transpose
torch.transpose(b,0,1)

tensor([[3, 9, 9],
        [1, 2, 3],
        [9, 0, 4],
        [7, 5, 9]])

In [19]:
#determinant
torch.det(torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32))

tensor(36.)

# **Inplace Operations**

To save the memory, store the result in the previous mem location. using "_" at the end of the fun uses inplace operation



In [20]:
m = torch.randint(size=(2,2), low=0, high=10)
n = torch.randint(size=(2,2), low=0, high=10)
print(m)
m.add_(n)
print(m)

tensor([[2, 7],
        [9, 7]])
tensor([[ 5, 10],
        [13, 10]])


In [21]:
m.relu_() #stores the result in m

tensor([[ 5, 10],
        [13, 10]])

**Copying a tensor**

1. Simplest way of copying a tensor is to use the assignment operator. But assign opr points to the same memory location(uses a reference object).
Example is given below

In [40]:
ten_1 = torch.tensor([[1,2,5,2,6,2,1],[2,2,5,6,1,7,3]])
copy_ten_1 = ten_1

#print(copy_ten_1)

#If we change any value in ten_1, it will change the value in copy_ten_1 as well as it points to the same memory loc as a reference point.

print(id(ten_1))
print(id(copy_ten_1))

#same location
ten_1[0][0]=0
print(copy_ten_1)
#Now we can use clone() to avoid this
clone_ten_1 = ten_1.clone()
ten_1[0][0] = 12 #changing value in main tensor
print(clone_ten_1) #original tensor retains
print(ten_1) #tensor with changed value



137570569572656
137570569572656
tensor([[0, 2, 5, 2, 6, 2, 1],
        [2, 2, 5, 6, 1, 7, 3]])
tensor([[0, 2, 5, 2, 6, 2, 1],
        [2, 2, 5, 6, 1, 7, 3]])
tensor([[12,  2,  5,  2,  6,  2,  1],
        [ 2,  2,  5,  6,  1,  7,  3]])


# **Tensor Operations on GPU**

In [41]:
torch.cuda.is_available()

True

In [44]:
device = torch.device('cuda')
a = torch.tensor([2,5,2,7],dtype=torch.float32, device=device)
b = torch.tensor([5,7,2,4],dtype=torch.float32,device = device)
torch.dot(a,b)


tensor(77., device='cuda:0')

In [45]:
#Moving CPU tensors to GPU
a = a.to(device)
a+5


tensor([ 7., 10.,  7., 12.], device='cuda:0')

# **Example to show power performance of GPU vs CPU**

In [47]:
import time
size = 10000

mat_cpu_1 = torch.randn(size,size)
mat_cpu_2 = torch.randn(size,size)

#measure time

start = time.time()
result_cpu = torch.matmul(mat_cpu_1,mat_cpu_2)
end = time.time()
result = end-start
print(f"CPU time: {result:.4f}")

#Now on GPU
device = torch.device('cuda')
mat_gpu_1 = mat_cpu_1.to(device) #move existing tensor to GPU
mat_gpu_2 = mat_cpu_2.to(device) #move existing tensor to GPU

start = time.time()
result_gpu = torch.matmul(mat_gpu_1,mat_gpu_2)
end = time.time()
result = end-start
print(f"GPU time: {result:.4f}")



CPU time: 15.0602
GPU time: 0.0465


# **Reshaping Tensors**

In [55]:
re = torch.rand(4,4)

re.reshape(8,2) #reshapes
re.flatten() #to 1d

#permute
per = torch.rand(2,6,4) #here 2 is on 0th index , 6 is on 1st and 4 is on 2nd
per.permute(2,0,1).shape #2,0,1 shows index, it swaps indices

torch.Size([4, 2, 6])

In [70]:
#unsqueeze

#adds a dimension to a given position
c = torch.rand(226,226,3)

c.unsqueeze(0).shape  #useful when batches are needed



torch.Size([1, 226, 226, 3])

In [71]:
#Squeeze
d = torch.rand(1,20)
print(d.shape)


d.squeeze(0).shape  #only works when dim==1

torch.Size([1, 20])


torch.Size([20])